package fun.happyhacker.spring.model.spring;

import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table users
 */
public class User {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.34+08:00", comments="Source field: users.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.34+08:00", comments="Source field: users.name")
    private String name;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.341+08:00", comments="Source field: users.mobile")
    private String mobile;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.341+08:00", comments="Source field: users.address")
    private String address;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.341+08:00", comments="Source field: users.age")
    private Byte age;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.34+08:00", comments="Source field: users.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.34+08:00", comments="Source field: users.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.34+08:00", comments="Source field: users.name")
    public String getName() {
        return name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.341+08:00", comments="Source field: users.name")
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.341+08:00", comments="Source field: users.mobile")
    public String getMobile() {
        return mobile;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.341+08:00", comments="Source field: users.mobile")
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.341+08:00", comments="Source field: users.address")
    public String getAddress() {
        return address;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.341+08:00", comments="Source field: users.address")
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.341+08:00", comments="Source field: users.age")
    public Byte getAge() {
        return age;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-07T14:15:04.341+08:00", comments="Source field: users.age")
    public void setAge(Byte age) {
        this.age = age;
    }
}